version: "3.2"
services:
  server_node:
    restart: always
    build: ./server
    depends_on:
      - mongo
    environment:
      NODE_ENV: production
    volumes:
      - ./server:/app
    ports:
      - "5001:5001"

  client_react:
    restart: always
    build: ./client
    ports:
      - "80:80"
    volumes:
      - ./client:/app
    depends_on:
      - server_node

  mongo:
    image: mongo
    ports:
      - 27017:27017
    env_file:
      - .env
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongo-data:/data/db

volumes:
  mongo-data:
